### ISSUE TITLE
4.2 Alpha Extenstion Uninstall Error.

### ISSUE THREAD

**Issue by RinaDev-xyz** [teamneoneko/Cats-Blender-Plugin#120]
When a user uninstalls Cats you get this error 

"Traceback (most recent call last):
  File "/home/rina/Desktop/Blender/blender-4.2.0-beta+v42.5fda92a44ff0-linux.x86_64-release/4.2/scripts/modules/addon_utils.py", line 511, in disable
    mod.unregister()
  File "/home/rina/.config/blender/4.2/extensions/user_default/cats_blender_plugin/__init__.py", line 298, in unregister
    if not bpy.context.scene.show_mmd_tabs:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_mmd_tabs'"

This is because we remove the MMD Tool Tab setting, I will fix this in the next Alpha release. Does not effect any functions or anything just slightly annoying.

**Comment by RinaDev-xyz** [comment]
Solved in [4.2.0.2](https://github.com/teamneoneko/Cats-Blender-Plugin-Unofficial-/releases/tag/4.2.0.2)
