### ISSUE TITLE
fix MMD model error

### ISSUE THREAD

**Issue by LenaBai** [teamneoneko/Cats-Blender-Plugin#68]
**I encountered an error while using the fix MMD model in Blender3.6.**

**This is my error code**

```
Python: Traceback (most recent call last):
  File "Z:\blender-3.6.0-windows-x64\3.6\python\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "Z:\blender-3.6.0-windows-x64\3.6\python\lib\site-packages\urllib3\connectionpool.py", line 994, in _prepare_proxy
    conn.connect()
  File "Z:\blender-3.6.0-windows-x64\3.6\python\lib\site-packages\urllib3\connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "Z:\blender-3.6.0-windows-x64\3.6\python\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "Z:\blender-3.6.0-windows-x64\3.6\python\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "Z:\blender-3.6.0-windows-x64\3.6\python\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "Z:\blender-3.6.0-windows-x64\3.6\python\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "Z:\blender-3.6.0-windows-x64\3.6\python\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: _ssl.c:990: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Z:\blender-3.6.0-windows-x64\3.6\python\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "Z:\blender-3.6.0-windows-x64\3.6\python\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "Z:\blender-3.6.0-windows-x64\3.6\python\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /_/TranslateWebserverUi/data/batchexecute (Caused by ProxyError('Cannot connect to proxy.', TimeoutError('_ssl.c:990: The handshake operation timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86152\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Cats-Blender-Plugin-Unofficial--blender-36-dev\extern_tools\google_trans_new\google_trans_new.py", line 145, in translate
    r = s.send(request=response.prepare(),
  File "Z:\blender-3.6.0-windows-x64\3.6\python\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "Z:\blender-3.6.0-windows-x64\3.6\python\lib\site-packages\requests\adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /_/TranslateWebserverUi/data/batchexecute (Caused by ProxyError('Cannot connect to proxy.', TimeoutError('_ssl.c:990: The handshake operation timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86152\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Cats-Blender-Plugin-Unofficial--blender-36-dev\tools\armature.py", line 350, in execute
    Translate.update_dictionary(to_translate)
  File "C:\Users\86152\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Cats-Blender-Plugin-Unofficial--blender-36-dev\tools\translate.py", line 430, in update_dictionary
    translation = translator.translate(text, lang_src=source_language, lang_tgt='en').strip()
  File "C:\Users\86152\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Cats-Blender-Plugin-Unofficial--blender-36-dev\extern_tools\google_trans_new\google_trans_new.py", line 216, in translate
    raise google_new_transError(tts=self)
Cats-Blender-Plugin-Unofficial--blender-36-dev.extern_tools.google_trans_new.google_trans_new.google_new_transError: Failed to connect. Probable cause: timeout
```

**Comment by RinaDev-xyz** [comment]
It looks like you failed to connect to Google translate for the translation part of the operation.

This could be because.

1: Your not connected to the internet.
2: Your banned from using the Google API.
3: Your using a VPN.
4: There is suspicious activity from your network.
5: Your using the dev version of cats which is using the new translate system which isn't finished yet and could cause some issues.
6: Google is being stupid.
7: Your firewall is blocking blender.
8: Your network settings are causing some issues.

Please note that you should only use fix mmd model if your setting up a new mmd/ vrm model which has never been set up for use in Unity before.

Now I am currently re-writing the translate system for cats so it handles issues like this more gracefully. Also maybe try a released version to see if this issue persists.

However the issue itself is most likely not Cats issue unless something I changed in the dev version broke something, however the way cats handles the error and inform the user isn't the greatest.

**Comment by LenaBai** [comment]
Thank you for your reply.
After I turned off the VPN according to your statement, there was no error, but when I used the fix MMD model, my Blender 3.6 crashed, and both the development and release versions had the same issue.

**Comment by RinaDev-xyz** [comment]
Ok blender crashing when using Fix MMD Model could be several different things, could you try and find your blender logs which are normally located C:\Users\[your username]\AppData\Local\Temp\  if you on Windows. Sometimes windows deletes these so you may not be able to find them. There will be called the file name of your current file for example test.blend logs will be called test.crash.txt.

If you can find them please can you either put them here or send them to hello@yusarina.xyz (Some people don't like putting log files on github). 

Apart from that the reason it crashes could be for the following reasons:
1: Your using the windows store version.
2: Sometimes the portable version of blender crashes (Something I can't seem to trace down).
3: Your model is over complex or has something on it either blender or cats doesn't like.
4: You model could have shapekey driver (Doubt this would cause a crash though).
5: There a bug in cats which your model causes.
6: Tabbing out of blender or clicking on blender too much while the operation is happening can cause it to crash as well.

Could you also try a different model, if the other model doesn't crash blender then it's most likely something to do with the model you are using, this could mean there is something on that model which either cats or blender doesn't like.

**Comment by RinaDev-xyz** [comment]
Closed due to no reply, feel free to re-open if more information can be given as stated above.
