### ISSUE TITLE
key "Subsurface" not found'

### ISSUE THREAD

**Issue by questionkiller** [teamneoneko/Cats-Blender-Plugin#87]
When I press convert to blender , error occurs
`Python: Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Cats-Blender-Plugin-Unofficial--blender-41\extern_tools\mmd_tools_local\operators\material.py", line 93, in execute
    cycles_converter.convertToBlenderShader(obj, use_principled=self.use_principled, clean_nodes=self.clean_nodes, subsurface=self.subsurface)
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Cats-Blender-Plugin-Unofficial--blender-41\extern_tools\mmd_tools_local\cycles_converter.py", line 126, in convertToBlenderShader
    __convertToPrincipledBsdf(i.material, subsurface)
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Cats-Blender-Plugin-Unofficial--blender-41\extern_tools\mmd_tools_local\cycles_converter.py", line 301, in __convertToPrincipledBsdf
    __switchToPrincipledBsdf(material.node_tree, s, subsurface=subsurface)
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Cats-Blender-Plugin-Unofficial--blender-41\extern_tools\mmd_tools_local\cycles_converter.py", line 328, in __switchToPrincipledBsdf
    #shader.inputs["Subsurface"].default_value = subsurface
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'bpy_prop_collection[key]: key "Subsurface" not found'`

**Comment by RinaDev-xyz** [comment]
You clearly didn't read this https://github.com/Yusarina/Cats-Blender-Plugin-Unofficial-/issues/81

Or any of the warnings in the readme or wiki about blender 4.1.

This is a mmd tools issue therefor I am going to close this issue. Please downgrade to blender 3.6 for a stable experience as I am unable to fix issues that are related to mmd tools.

MMD Tools is a 3rd party add-on which cats uses for certain functions. The author mmd tools is not going to support blender 4.x into the 4.2 LTS.
